export const fakeDonations = [
  {
    id: "1",
    paymentPlatform: "Stripe",
    donationType: "One-time",
    dateAdded: "2025-08-01 10:30 UTC",
    name: "Alice Nguyen",
    amount: "$50",
    package: "Supporter",
  },
  {
    id: "2",
    paymentPlatform: "PayPal",
    donationType: "Monthly",
    dateAdded: "2025-08-02 14:45 UTC",
    name: "John Tran",
    amount: "$100",
    package: "Champion",
  },
  {
    id: "3",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "4",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "5",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "6",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "7",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "8",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "9",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "10",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "11",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "12",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "13",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "14",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "15",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
  {
    id: "16",
    paymentPlatform: "Bank Transfer",
    donationType: "One-time",
    dateAdded: "2025-08-03 09:20 UTC",
    name: "Linh Pham",
    amount: "$25",
    package: "Basic",
  },
];
